spring:
  datasource:
    #    username: root
    #    password: 123456
    #    url: jdbc:mysql://localhost:3306/gobang?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xurongchao
    password: xrc@123456
    url: jdbc:mysql://rm-bp13y3jj290u7hyqqyo.mysql.rds.aliyuncs.com/gobang?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 4


mybatis:
  mapper-locations: classpath:mapping/*.xml
